services:

  postgres:
    image: postgres:16
    container_name: rescueplate-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  userservice:
    image: rescueplate-userservice:latest
    container_name: rescueplate-userservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__PostgreSQLConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      Jwt__SecretKey: ${JWT_SECRET_KEY}
      Jwt__Issuer: "RescuePlate.UserService"
      Jwt__Audience: "RescuePlate.Client"

      FrontendUrl: ${FRONTEND_URL}

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    ports:
      - "5000:8080"

  frontend:
    image: rescueplate-frontend:latest
    container_name: rescueplate-frontend
    depends_on:
      - userservice
    ports:
      - "3000:80"

volumes:
  postgres_data: