services:

  postgres:
    image: postgres:16
    container_name: rescueplate-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  userservice:
    image: rescueplate-userservice:latest
    container_name: rescueplate-userservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__PostgreSQLConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      Jwt__SecretKey: ${JWT_SECRET_KEY}
      Jwt__Issuer: "RescuePlate.UserService"
      Jwt__Audience: "RescuePlate.Client"

      FrontendUrl: ${FRONTEND_URL}

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    ports:
      - "5000:8080"

  requestworkflowservice:
    image: rescueplate-requestworkflowservice:latest
    container_name: rescueplate-requestworkflowservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__PostgreSQLConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      Jwt__SecretKey: ${JWT_SECRET_KEY}
      Jwt__Issuer: "RescuePlate.UserService"
      Jwt__Audience: "RescuePlate.Client"

      Services__UserServiceUrl: "http://userservice:8080"
      Services__DonationServiceUrl: "http://donationservice:8080"
      FrontendUrl: ${FRONTEND_URL}

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    ports:
      - "5002:8080"


  frontend:
    image: rescueplate-frontend:latest
    container_name: rescueplate-frontend
    depends_on:
      - userservice
    ports:
      - "3000:80"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: rescueplate-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

volumes:
  postgres_data: