using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using DeliveryWorkflowService.Data;

var builder = WebApplication.CreateBuilder(args);

// 1. Database Configuration (PostgreSQL - RescuePlateDB via Npgsql EF Core)
var connectionString = builder.Configuration.GetConnectionString("PostgreSQLConnection")
    ?? builder.Configuration["ConnectionStrings__PostgreSQLConnection"]
    ?? "Host=localhost;Port=5432;Database=RescuePlateDB;Username=postgres;Password=postgres";

builder.Services.AddDbContext<DeliveryDbContext>(options =>
{
    options.UseNpgsql(connectionString);
});

// 2. Health Checks Registration
builder.Services.AddHealthChecks()
    .AddDbContextCheck<DeliveryDbContext>(
        name: "PostgreSQL",
        tags: new[] { "db", "data" });

// 3. JWT Authentication & Authorization Setup
var secretKey = builder.Configuration["Jwt:SecretKey"]
    ?? builder.Configuration["JWT_SECRET_KEY"];

if (string.IsNullOrWhiteSpace(secretKey))
{
    // Fallback for development local execution if not injected via env
    secretKey = "RescuePlate_Super_Secret_Key_For_Jwt_Authentication_2026_Sprint1_RescueFood";
}

var issuer = builder.Configuration["Jwt:Issuer"] ?? "RescuePlate.UserService";
var audience = builder.Configuration["Jwt:Audience"] ?? "RescuePlate.Client";
var frontendUrl = builder.Configuration["FrontendUrl"] ?? "http://localhost:5173";

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = false;
        options.SaveToken = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = issuer,
            ValidAudience = audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey)),
            RoleClaimType = ClaimTypes.Role,
            NameClaimType = ClaimTypes.NameIdentifier,
            ClockSkew = TimeSpan.Zero
        };
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("DonorOnly", policy => policy.RequireRole("DONOR"));
    options.AddPolicy("OrganizationOnly", policy => policy.RequireRole("ORGANIZATION"));
    options.AddPolicy("AdminOnly", policy => policy.RequireRole("ADMIN"));
});

// 4. CORS Policy Setup
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.WithOrigins(frontendUrl, "http://localhost:3000")
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// 5. Controllers & JSON Serialization Options
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
        options.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    });

// 6. Swagger / OpenAPI Documentation
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "RescuePlate Delivery Workflow Service API",
        Version = "v1",
        Description = "ASP.NET Core 10 Microservice for managing tracking and delivery collection workflows (Sprint 4)"
    });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();

// 7. Automatic Database Table Initialization & Schema Setup
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<DeliveryDbContext>();
    try
    {
        dbContext.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""DeliveryArrangements"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""RequestId"" integer NOT NULL,
                ""DonationId"" integer NOT NULL,
                ""DonationTitle"" character varying(200) NOT NULL DEFAULT '',
                ""DonorId"" character varying(100) NOT NULL,
                ""DonorName"" character varying(150) NOT NULL,
                ""OrganizationId"" character varying(100) NOT NULL,
                ""OrganizationName"" character varying(150) NOT NULL,
                ""PickupAddress"" character varying(255) NOT NULL,
                ""DeliveryAddress"" character varying(255) NOT NULL,
                ""ContactName"" character varying(150) NOT NULL,
                ""ContactPhone"" character varying(50) NOT NULL,
                ""ScheduledCollectionTime"" timestamp with time zone NOT NULL,
                ""Notes"" character varying(500),
                ""Status"" character varying(50) NOT NULL DEFAULT 'CollectionArranged',
                ""ArrangedAt"" timestamp with time zone NOT NULL,
                ""CollectedAt"" timestamp with time zone,
                ""ReceivedAt"" timestamp with time zone,
                ""CompletedAt"" timestamp with time zone,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_DeliveryArrangements_RequestId"" ON ""DeliveryArrangements"" (""RequestId"");
            CREATE INDEX IF NOT EXISTS ""IX_DeliveryArrangements_DonationId"" ON ""DeliveryArrangements"" (""DonationId"");
            CREATE INDEX IF NOT EXISTS ""IX_DeliveryArrangements_DonorId"" ON ""DeliveryArrangements"" (""DonorId"");
            CREATE INDEX IF NOT EXISTS ""IX_DeliveryArrangements_OrganizationId"" ON ""DeliveryArrangements"" (""OrganizationId"");
            CREATE INDEX IF NOT EXISTS ""IX_DeliveryArrangements_Status"" ON ""DeliveryArrangements"" (""Status"");

            CREATE TABLE IF NOT EXISTS ""DeliveryStatusHistories"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""DeliveryArrangementId"" integer NOT NULL,
                ""PreviousStatus"" character varying(50) NOT NULL,
                ""NewStatus"" character varying(50) NOT NULL,
                ""ChangedByUserId"" character varying(100) NOT NULL,
                ""ChangedByRole"" character varying(50) NOT NULL,
                ""Notes"" character varying(500),
                ""Timestamp"" timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS ""IX_DeliveryStatusHistories_DeliveryArrangementId"" ON ""DeliveryStatusHistories"" (""DeliveryArrangementId"");
            CREATE INDEX IF NOT EXISTS ""IX_DeliveryStatusHistories_Timestamp"" ON ""DeliveryStatusHistories"" (""Timestamp"");
        ");
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        logger.LogWarning(ex, "Could not initialize DeliveryWorkflowService database schema.");
    }
}

// 8. Middleware Pipeline Setup
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "RescuePlate Delivery Workflow Service API v1");
    });
}

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

// Health Check Endpoint mapping
app.MapHealthChecks("/health");

app.MapControllers();

app.Run();

public partial class Program { }
