using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using DonationService.Data;
using DonationService.Services;

var builder = WebApplication.CreateBuilder(args);

// 1. Database Configuration (PostgreSQL - RescuePlateDB via Npgsql EF Core)
var connectionString = builder.Configuration.GetConnectionString("PostgreSQLConnection")
    ?? "Host=localhost;Port=5432;Database=RescuePlateDB;Username=postgres;Password=postgres";

builder.Services.AddDbContext<DonationDbContext>(options =>
{
    options.UseNpgsql(connectionString);
});

// 2. JWT Authentication & Authorization
var secretKey = builder.Configuration["Jwt:SecretKey"] ?? "RescuePlate_Super_Secret_Key_For_Jwt_Authentication_2026_Sprint1_RescueFood";
var issuer = builder.Configuration["Jwt:Issuer"] ?? "RescuePlate.UserService";
var audience = builder.Configuration["Jwt:Audience"] ?? "RescuePlate.Client";
var frontendUrl = builder.Configuration["FrontendUrl"] ?? "http://localhost:5173";

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = false;
        options.SaveToken = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = issuer,
            ValidAudience = audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey)),
            RoleClaimType = ClaimTypes.Role,
            NameClaimType = ClaimTypes.NameIdentifier,
            ClockSkew = TimeSpan.Zero
        };
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("DonorOnly", policy => policy.RequireRole("DONOR"));
    options.AddPolicy("OrganizationOnly", policy => policy.RequireRole("ORGANIZATION"));
    options.AddPolicy("AdminOnly", policy => policy.RequireRole("ADMIN"));
});

// 3. CORS Policy for Frontend (Vite on http://localhost:5173)
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.WithOrigins(frontendUrl, "http://localhost:3000")
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// 4. Register Services
builder.Services.AddScoped<IDonationService, DonationServiceImpl>();
builder.Services.AddHostedService<DonationExpiryBackgroundService>();

// 5. Controllers & JSON Options
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
    });

// 6. Swagger / OpenAPI with JWT Security Scheme
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "RescuePlate Donation Service API",
        Version = "v1",
        Description = "ASP.NET Core 10 Microservice for managing food surplus donations, inventory claiming, and redistribution (Sprint 2)"
    });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();

// Ensure PostgreSQL tables are created and schema is up to date
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<DonationDbContext>();
    try
    {
        dbContext.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""Donations"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""DonorId"" character varying(100) NOT NULL,
                ""DonorName"" character varying(150) NOT NULL,
                ""DonorEmail"" character varying(150),
                ""FoodTitle"" character varying(200) NOT NULL,
                ""Category"" character varying(50) NOT NULL,
                ""TotalQuantity"" integer NOT NULL,
                ""ClaimedQuantity"" integer NOT NULL DEFAULT 0,
                ""RemainingQuantity"" integer NOT NULL,
                ""Unit"" character varying(50) NOT NULL,
                ""ExpiryTime"" timestamp with time zone NOT NULL,
                ""CollectionMode"" character varying(50) NOT NULL,
                ""Status"" character varying(50) NOT NULL,
                ""Location"" character varying(255),
                ""Notes"" character varying(500),
                ""DietaryTags"" character varying(255),
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""UpdatedAt"" timestamp with time zone
            );
            CREATE INDEX IF NOT EXISTS ""IX_Donations_Category"" ON ""Donations"" (""Category"");
            CREATE INDEX IF NOT EXISTS ""IX_Donations_Status"" ON ""Donations"" (""Status"");
            CREATE INDEX IF NOT EXISTS ""IX_Donations_DonorId"" ON ""Donations"" (""DonorId"");
        ");
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Could not initialize Donations table schema");
    }
}

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "RescuePlate Donation Service API v1");
    });
}

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

// Microservice Health Check Endpoint
app.MapGet("/health", () => Results.Ok(new
{
    service = "RescuePlate.DonationService",
    status = "Healthy",
    database = "PostgreSQL",
    timestamp = DateTime.UtcNow
})).WithName("HealthCheck");

app.MapControllers();

app.Run();
